replicaCount: 3


image: terraform-project-aselnur/artemis/artemis
 pullPolicy: IfNotPresent
  repository: us-central1-docker.pkg.dev/Overrides the image tag whose default is the chart appVersion.
  tag: 10.0.0
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:    
    ingress.kubernetes.io/ssl-redirect: "false"
    # kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns01
    acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: artemis-qa.aselnur.com 
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: artemis-tls
      hosts:
        - artemis-dev.aselnur.com 